### ISSUE TITLE
yarn dev.prepare fails (rcedit-x64.exe ENOENT)

### ISSUE THREAD

**Issue by TekSiDoT** [nrwl/angular-console#180]
`yarn dev.prepare` fails during `nps is executing `win.pack` : electron-builder --win --dir -p never` with the following error on Win10 latest:

```
• downloading               path=C:\Users\hab\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.1.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.1.0/winCodeSign-2.1.0.7z
  • cannot move downloaded into final location (another process downloaded faster?) error=rename C:\Users\hab\AppData\Local\electron-builder\cache\winCodeSign\161726787 C:\Users\hab\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.1.0: Zugriff verweigert path=C:\Users\hab\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.1.0 tempUnpackDir=C:\Users\hab\AppData\Local\electron-builder\cache\winCodeSign\161726787
Error: Exit code: ENOENT. spawn C:\Users\hab\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-2.1.0\rcedit-x64.exe ENOENT
    at D:\git\angularConsole\node_modules\builder-util\src\util.ts:125:16
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.signAndEditResources (D:\git\angularConsole\node_modules\electron-builder-lib\src\winPackager.ts:272:158)
    at _bluebirdLst.default.map.file (D:\git\angularConsole\node_modules\electron-builder-lib\src\winPackager.ts:367:21)
    at go$readdir$cb (D:\git\angularConsole\node_modules\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\winPackager.ts:365:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (D:\git\angularConsole\node_modules\electron-builder-lib\src\winPackager.ts:359:73)
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\platformPackager.ts:233:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (D:\git\angularConsole\node_modules\electron-builder-lib\src\platformPackager.ts:158:165)
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (D:\git\angularConsole\node_modules\electron-builder-lib\src\platformPackager.ts:111:95)
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\packager.ts:369:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.doBuild (D:\git\angularConsole\node_modules\electron-builder-lib\src\packager.ts:337:39)
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\packager.ts:313:52
    at Generator.next (<anonymous>)
    at D:\git\angularConsole\node_modules\graceful-fs\graceful-fs.js:99:16
    at D:\git\angularConsole\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (D:\git\angularConsole\node_modules\electron-builder-lib\src\packager.ts:290:133)
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\packager.ts:286:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (D:\git\angularConsole\node_modules\electron-builder-lib\src\packager.ts:243:14)
    at D:\git\angularConsole\node_modules\electron-builder-lib\src\index.ts:52:40
    at Generator.next (<anonymous>)
From previous event:
    at build (D:\git\angularConsole\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (D:\git\angularConsole\node_modules\electron-builder\src\builder.ts:224:10)
    at then (D:\git\angularConsole\node_modules\electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
The script called "win.pack" which runs "electron-builder --win --dir -p never" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.2/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "dev.prepare" which runs "nps win.clean && nps dev.compile-server-and-electron && nps frontend.build && nps win.copy-frontend && nps win.pack" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.2/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
error Command failed with exit code 1.
```

**Comment by TekSiDoT** [comment]
After running `yarn build` (which downloaded the respective files), `yarn dev.prepare` works fine.

**Comment by TekSiDoT** [comment]
@mrmeku :/
