### ISSUE TITLE
failing build on macOS and CI

### ISSUE THREAD

**Issue by DanielRuf** [nrwl/angular-console#279]
On macOS I get the following:

```
nps is executing `mac.copy-frontend` : cp -r dist/apps/angular-console dist/server/src/public
nps is executing `mac.pack` : electron-builder --mac --dir -p never
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/packages/builder-effective-config.yaml
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/druf/projects/angular-console/angular-console/dist/server
  • packaging       platform=darwin arch=x64 electron=2.0.8 appOutDir=dist/packages/mac
  • asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available
Error: ENOENT: no such file or directory, symlink '../bin/atob.js' -> '/Users/druf/projects/angular-console/angular-console/dist/packages/mac/Electron.app/Contents/Resources/app/node_modules/atob/.bin/atob'
    at _bluebirdLst.default.map.it (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/util/appFileCopier.ts:81:4)
From previous event:
    at /Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/util/appFileCopier.ts:81:4
    at Generator.next (<anonymous>)
From previous event:
    at copyAppFiles (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/out/util/appFileCopier.js:260:17)
    at taskManager.addTask._bluebirdLst.default.each.it (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/platformPackager.ts:296:86)
From previous event:
    at MacPackager.copyAppFiles (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/platformPackager.ts:296:43)
    at /Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/platformPackager.ts:213:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at MacPackager.doPack (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/druf/projects/angular-console/angular-console/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/druf/projects/angular-console/angular-console/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/druf/projects/angular-console/angular-console/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/node_modules/yargs/yargs.js:1085:24)
    at Object.get [as argv] (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/druf/projects/angular-console/angular-console/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
The script called "mac.pack" which runs "electron-builder --mac --dir -p never" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "dev.prepare" which runs "nps mac.clean && nps dev.compile-server && nps frontend.build && nps mac.copy-frontend && nps mac.pack" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

And CI currently looks like this:

https://circleci.com/gh/nrwl/angular-console/403

**Comment by mrmeku** [comment]
Fixed CI via #278
