### ISSUE TITLE
Error thrown when running ./angularconsole on Arch Linux

### ISSUE THREAD

**Issue by bartduisters** [nrwl/angular-console#444]
When running the angularconsole on Linux after extracting the tar.gz, an error is thrown.
/path/to/extracted-folder/
`./angularconsole`

thrown error
`starting server on port 7777
__ANGULAR_CONSOLE__NRWL_API not set, defaulting to production
__ANGULAR_CONSOLE__AUTH0_CLIENT_ID not set, defaulting to production
__ANGULAR_CONSOLE__AUTH0_DOMAIN not set, defaulting to production
__ANGULAR_CONSOLE__AUTH0_AUDIENCE not set, defaulting to production
Checking for update
Error: TypeError: this.app.whenReady is not a function
    at ElectronAppAdapter.whenReady (AngularConsole-7.1.0/resources/app/node_modules/electron-updater/src/ElectronAppAdapter.ts:9:21)
    at AngularConsole-7.1.0/resources/app/node_modules/electron-updater/src/AppUpdater.ts:337:20
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (AngularConsole-7.1.0/resources/app/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at AngularConsole-7.1.0/resources/app/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (AngularConsole-7.1.0/resources/app/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (AngularConsole-7.1.0/resources/app/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Timeout.setTimeout (AngularConsole-7.1.0/resources/app/src/index.js:188:64)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)`

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/angular-console/commit/cc2f336cf94089c7c68efbb6b90d92d36f731e00
