### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by YonatanKra** [nrwl/angular-console#466]
I'm trying to develop the console locally. Here are the steps taken:
1) git clone https://github.com/nrwl/angular-console.git
2) yarn
3) yarn start dev.prepare.electron

It finishes the first commands successfuly: 
`[server.gen-and-build.electron] nps server.gen-and-build.electron exited with code 0`
But later on it gives an error:
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:365:12)
    at ReadStream.process.stdin.on (c:\Users\yonatan.kr\Documents\github\angular-console\node_modules\concurrently\src\main.js:306:26)
    at ReadStream.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at ReadStream.Readable.push (_stream_readable.js:213:10)
    at TTY.onread (net.js:599:20)
The script called "dev.build.electron" which runs "node node_modules\concurrently\src\main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "server.gen-and-build.electron,frontend.build" "nps server.gen-and-build.electron" "nps frontend.build"" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "dev.prepare.electron" which runs "nps win.clean && nps dev.build.electron && nps win.electron-pack && nps win.copy-frontend.electron && nps dev.patch-cli" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
error Command failed with exit code 1.
```

I'm getting a different error on every run. Here's the current error:
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at ReadStream.process.stdin.on (C:\Users\yonatan.kr\Documents\github\angular-console\node_modules\concurrently\sr
c\main.js:306:26)
    at ReadStream.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
    at TTY.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:269:11)
The script called "dev.build.electron" which runs "node node_modules\concurrently\src\main.js --kill-others-on-fail -
-prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "server.gen-and-build.electron,frontend.build
" "nps server.gen-and-build.electron" "nps frontend.build"" failed with exit code 1 https://github.com/kentcdodds/nps
/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "dev.prepare.electron" which runs "nps win.clean && nps dev.build.electron && nps win.electron-pack
 && nps win.copy-frontend.electron && nps dev.patch-cli" failed with exit code 1 https://github.com/kentcdodds/nps/bl
ob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```

Help?

**Comment by mrmeku** [comment]
I reworked our build system so now developing should be a bit easier. Here's the step you need to do to get started:

Clone the repo
yarn install
npx nps dev.up

If you still have trouble please reopen the issue and tell me. Sorry that it was hard to get started contributing!

**Comment by YonatanKra** [comment]
Works now. Thanks!

**Comment by YonatanKra** [comment]
Ok, it seemed to work. 
I ran `yarn start dev.up`.
It built something. I can see it at `http://localhost:4201/workspace`.
I'm making changes, see the compilation process in my console - but in the browser I cannot see my changes. Am I missing something?
