### ISSUE TITLE
Unable to create new workspace

### ISSUE THREAD

**Issue by sajidali** [nrwl/angular-console#713]
angular-console version I am using is #`7.4.30`

I tried creating new workspace, but it failed and an error message is thrown that it cannot find typescript `Cannot find module 'typescript'`

I have tried this after installing typescript as global npm module, but I am getting same error.

Following is the full output from the angular-console.
-----------
```
new-workspace test --directory=test --collection=@nrwl/workspace --style=scss --npmScope=rtscope --no-skipInstall --no-skipGit --preset=full-stack --no-interactive

npm init -y
Wrote to /private/var/folders/r_/rdqvwkd51279h2slsttw8lkc0000gn/T/tmp-84070j9oW8BV9iMss/package.json:

{
  "name": "tmp-84070j9oW8BV9iMss",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm install @angular/cli@latest

> @angular/cli@8.0.0 postinstall /private/var/folders/r_/rdqvwkd51279h2slsttw8lkc0000gn/T/tmp-84070j9oW8BV9iMss/node_modules/@angular/cli
> node ./bin/postinstall/script.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp-84070j9oW8BV9iMss@1.0.0 No description
npm WARN tmp-84070j9oW8BV9iMss@1.0.0 No repository field.

+ @angular/cli@8.0.0
added 227 packages from 175 contributors and audited 2732 packages in 48.012s
found 0 vulnerabilities

npm install @nrwl/workspace@latest
npm WARN tmp-84070j9oW8BV9iMss@1.0.0 No description
npm WARN tmp-84070j9oW8BV9iMss@1.0.0 No repository field.

+ @nrwl/workspace@8.0.0
added 94 packages from 57 contributors and audited 2924 packages in 18.49s
found 0 vulnerabilities

ng new test --directory=test --collection=@nrwl/workspace --style=scss --npmScope=rtscope --no-skipInstall --no-skipGit --preset=full-stack --no-interactive
Cannot find module 'typescript'
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/private/var/folders/r_/rdqvwkd51279h2slsttw8lkc0000gn/T/tmp-84070j9oW8BV9iMss/node_modules/@nrwl/workspace/src/utils/ast-utils.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/private/var/folders/r_/rdqvwkd51279h2slsttw8lkc0000gn/T/tmp-84070j9oW8BV9iMss/node_modules/@nrwl/workspace/src/schematics/ng-new/ng-new.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
child_process.js:656
    throw err;
    ^

Error: Command failed: /var/folders/r_/rdqvwkd51279h2slsttw8lkc0000gn/T/tmp-84070j9oW8BV9iMss/node_modules/.bin/ng new test --directory=test --collection=@nrwl/workspace --style=scss --npmScope=rtscope --no-skipInstall --no-skipGit --preset=full-stack --no-interactive --no-interactive
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (/Applications/Angular Console.app/Contents/Resources/app/assets/new-workspace:40:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

Process failed 🐳
```

**Comment by sajidali** [comment]
With the recent release of angular-console #8.0.0, this issue is fixed. 
Now typescript is installed before running `ng new ...` command. so I am closing this issue, as it is fixed in new version.

**Comment by HackPoint** [comment]
> With the recent release of angular-console #8.0.0, this issue is fixed.
> Now typescript is installed before running `ng new ...` command. so I am closing this issue, as it is fixed in new version.

My is just failing:
/Applications/Angular Console.app/Contents/Resources/app/assets/new-workspace fastry --directory=fastry --collection=@nrwl/workspace --style=scss --no-skipInstall --no-skipGit --no-interactive

                         bash: /Applications/Angular: No such file or directory

Process failed 🐳

**Comment by baunov** [comment]
Just updated Angular Console. Same issue.

**Comment by elberthAgreda** [comment]
Same issue...
bash: /Applications/Angular: No such file or directory
Process failed 🐳

**Comment by frontendplace** [comment]
failed after updating my angular console version 8.1.0
`/Applications/Angular Console.app/Contents/Resources/app/assets/new-workspace my-svb --directory=my-svb --collection=@schematics/angular --no-enableIvy --no-skipInstall --skipGit --commit=false --no-inlineStyle --no-inlineTemplate --routing --style=scss --no-skipTests --createApplication --no-minimal --no-interactive

                                      bash: /nvm.sh: No such file or directory
bash: /nvm.sh: No such file or directory
bash: /Applications/Angular: No such file or directory

Process failed 🐳
`
