### ISSUE TITLE
merge2 is not a function

### ISSUE THREAD

**Issue by johnpapa** [nrwl/angular-console#718]
this error popped up today.

```
Activating extension `nrwl.angular-console` failed:  merge2 is not a function

Here is the error stack:  TypeError: merge2 is not a function
        at Object.merge (/Users/papa/.vscode/extensions/nrwl.angular-console-8.0.0/main.js:14398:24)
        at stream (/Users/papa/.vscode/extensions/nrwl.angular-console-8.0.0/main.js:5048:24)
        at activate (/Users/papa/.vscode/extensions/nrwl.angular-console-8.0.0/main.js:4964:87)
        at Function._callActivateOptional (/Users/papa/_git/vscode-peacock/.vscode-test/vscode-1.34.0/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:936)
        at Function._callActivate (/Users/papa/_git/vscode-peacock/.vscode-test/vscode-1.34.0/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:625)
        at define._doActivateExtension.Promise.all.then.e (/Users/papa/_git/vscode-peacock/.vscode-test/vscode-1.34.0/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:730:635)
```

**Comment by mattdsteele** [comment]
Seeing the same issue with the VSCode plugin. (vscode 1.35.1, Angular Console extension 8.0.5, Win10).

```
 Here is the error stack:  TypeError: merge2 is not a function
	at Object.merge (C:\Users\igen261\.vscode\extensions\nrwl.angular-console-8.0.5\main.js:14398:24)
	at stream (C:\Users\igen261\.vscode\extensions\nrwl.angular-console-8.0.5\main.js:5048:24)
	at activate (C:\Users\igen261\.vscode\extensions\nrwl.angular-console-8.0.5\main.js:4964:87)
	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:936)
	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:625)
	at define._doActivateExtension.Promise.all.then.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:737:635)
```

**Comment by mrmeku** [comment]
I believe this issue should be fixed now with our latest release. If its not and I was just unable to replicate the issue please let me know. Fixing this issue is a high priority for me and I want to make sure its addressed properly
