### ISSUE TITLE
TypeError: merge2 is not a function

### ISSUE THREAD

**Issue by johnpapa** [nrwl/angular-console#741]
In the output

```

Activating extension `nrwl.angular-console` failed:  merge2 is not a function

Here is the error stack:  TypeError: merge2 is not a function
        at Object.merge (/Users/papa/.vscode/extensions/nrwl.angular-console-8.0.6/main.js:14398:24)
        at stream (/Users/papa/.vscode/extensions/nrwl.angular-console-8.0.6/main.js:5048:24)
        at activate (/Users/papa/.vscode/extensions/nrwl.angular-console-8.0.6/main.js:4964:87)
        at Function._callActivateOptional (/Users/papa/_git/vscode-peacock/.vscode-test/vscode-1.36.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:518)
        at Function._callActivate (/Users/papa/_git/vscode-peacock/.vscode-test/vscode-1.36.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:207)
        at define._doActivateExtension.Promise.all.then.e (/Users/papa/_git/vscode-peacock/.vscode-test/vscode-1.36.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:747:245)
```

**Comment by mrmeku** [comment]
I believe this issue should be fixed now with our latest release. If its not and I was just unable to replicate the issue please let me know. Fixing this issue is a high priority for me and I want to make sure its addressed properly
