### ISSUE TITLE
Create new workspace failed 2

### ISSUE THREAD

**Issue by bobsort** [nrwl/angular-console#773]
npm install @angular/cli@latest
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/@angular%2fcli failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     ****\npm-cache\_logs\2019-07-24T06_30_35_254Z-debug.log
child_process.js:669
    throw err;
    ^

Error: Command failed: npm install @angular/cli@latest
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (****\angular-console\resources\app\assets\new-workspace:26:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)

Process failed

Yes, computer running Aconsole doesn't have internet access.
I am on a metered internet and I can't allow apps connect to internet everytime the want to do the same task.

I believe a better solution is to include what is required to run the app in the installation package or at least as a separate downloadable package. Something maybe like maven.

**Comment by mrmeku** [comment]
@bobsort We don't want to have to cut a new release of angular console whenever the angular cli updates so instead we fetch the latest version to generate a workspace for you. With our current team resources we cannot support an offline mode

**Comment by bobsort** [comment]
Why would you want to package latest version with console? A better solution would be adding a link to latest version in your website so people can download and install them in their computer when they do have access to internet, not every time that they are trying to create new project.
