### ISSUE TITLE
Create new workspace failed 3

### ISSUE THREAD

**Issue by bobsort** [nrwl/angular-console#775]
after running 
 npm install @angular/cli@latest
from command line and answering the question from there with N (default), openend create new workspace and click create. it failed again. App1 folder is still empty and Temp folder contains 97Mb downloaded files.

```
new-workspace app1 --directory=app1 --collection=@nrwl/workspace --no-skipInstall --no-skipGit --no-interactive

npm init -y
Wrote to ****\Temp\tmp-4464D6vvuXb1fLEu\package.json:

{
  "name": "tmp-4464D6vvuXb1fLEu",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm install @angular/cli@latest

> @angular/cli@8.1.2 postinstall ****\Temp\tmp-4464D6vvuXb1fLEu\node_modules\@angu
lar\cli
> node ./bin/postinstall/script.js

npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN tmp-4464D6vvuXb1fLEu@1.0.0 No description
npm WARN tmp-4464D6vvuXb1fLEu@1.0.0 No repository field.

+ @angular/cli@8.1.2
added 239 packages from 185 contributors and audited 2739 packages in 31.829s
found 0 vulnerabilities

npm install @nrwl/workspace@latest
npm WARN tmp-4464D6vvuXb1fLEu@1.0.0 No description
npm WARN tmp-4464D6vvuXb1fLEu@1.0.0 No repository field.

+ @nrwl/workspace@8.3.0
added 88 packages from 49 contributors and audited 2992 packages in 30.067s
found 0 vulnerabilities

npm install typescript@3.4.5
npm WARN tmp-4464D6vvuXb1fLEu@1.0.0 No description
npm WARN tmp-4464D6vvuXb1fLEu@1.0.0 No repository field.

+ typescript@3.4.5
added 1 package from 1 contributor and audited 2993 packages in 14.289s
found 0 vulnerabilities

ng new app1 --directory=app1 --collection=@nrwl/workspace --no-skipInstall --no-
skipGit --no-interactive
An unhandled exception occurred: Could not find module "@nrwl/workspace" from "****\\Angular\\Projects\\App1".
See "****:\Temp\ng-OF9u12\angular-errors.log" for further details.
child_process.js:669
    throw err;
    ^

Error: Command failed: ****:\Temp\tmp-4464D6vvuXb1fLEu\node_modules\.bin\ng new app
1 --directory=app1 --collection=@nrwl/workspace --no-skipInstall --no-skipGit --
no-interactive --no-interactive
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (****:\Angular\angular-console\resources\app\assets\new-workspace:46:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)

Process failed
```

**Comment by bobsort** [comment]
Content of angular-errors.log is as follows

```
[error] Error: Could not find module "@nrwl/workspace" from "****\\Angular\\Projects\\App1".
    at Object.resolve (****\Angular\node_modules\@angular-devkit\core\node\resolve.js:151:11)
    at NodeModulesEngineHost._resolvePackageJson (****\Angular\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (****\Angular\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (****\Angular\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (****\Angular\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection (****\Angular\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at NewCommand.getCollection (****\Angular\node_modules\@angular\cli\models\schematic-command.js:129:35)
    at NewCommand.initialize (****\Angular\node_modules\@angular\cli\models\schematic-command.js:45:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
```

**Comment by utkarsh-srivastava** [comment]
I am facing the same issue. Are you trying to create the workspace in C drive?

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

We will be incorporating workspace creation logic into our VSCode release in our November release. Apologies for the delay in a proper resolution
