### ISSUE TITLE
yarn command fails

### ISSUE THREAD

**Issue by bampakoa** [nrwl/angular-console#791]
When I try to execute `yarn` command, I get the following error:

> error .....\angular-console\node_modules\node-pty: Command failed.
> Exit code: 1
> Command: node scripts/install.js
> Arguments:
> Directory: ....\angular-console\node_modules\node-pty
> Output:
> ....\angular-console\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.8.0
> gyp info using node@10.15.3 | win32 | x64
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd ...\angular-console\node_modules\node-pty

Do I need to install **Python** also?

**Comment by dxvladislavvolkov** [comment]
This problem appeared after these [changes](https://github.com/nrwl/angular-console/pull/745)

**Comment by bampakoa** [comment]
@mrmeku thanks very much for your feedback. It also fails in a terminal as you suspected 😟. Notice that I am trying to run it in a Windows machine and I do not have Python installed.

Though I think that this issue should be re-opened since this may not have to do with the Angular Console directly but with the development environment around it. So, it would be nice to have some notes, possible in the CONTRIBUTING guide, about possible problems that someone will face when trying to contribute to the library and make it easier for them 😉
