### ISSUE TITLE
Cant Create New Workspace

### ISSUE THREAD

**Issue by matkeng** [nrwl/angular-console#793]
Not sure why I always get this error:

new-workspace matt2 --directory=matt2 --collection=@schematics/angular --no-enableIvy --no-skipInstall --no-skipGit --no-inlineStyle --no-inlineTemplate --no-routing --no-skipTests --createApplication --no-minimal --no-interactive

C:\Users\matt\AppData\Local\Programs\angular-console\resources\app\assets\new-wo
rkspace:4
const { execSync } = require('child_process');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Process failed 🐳

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
