### ISSUE TITLE
Unable to run custom workspace schematics

### ISSUE THREAD

**Issue by electrichead** [nrwl/angular-console#895]
I used the VSCode extension to create a schematic in my workspace. However I am unable to run this schematic. If I use "generate" I can only see
![image](https://user-images.githubusercontent.com/453966/69012186-0636cb80-0941-11ea-9f51-9e46597b7f33.png)
(my schematic is called "workspace-feature-lib")

Although the options are all present here, it is unable to execute it because it says
`An unhandled exception occurred: Schematic "workspace-feature-lib" not found in collection "@nrwl/workspace".`

Am I missing something or is this not possible with the extension?

**Comment by Maus3rVonDutch** [comment]
I'm also experiencing this (again), this is with the latest version 9.1.
I'm on Windows 10 and using Powershell as the shell terminal

I'm seeing 2 nearly identical files in the code, one containing a typo:

libs\server\src\lib\utils\read-**scehmatic**-collections.ts
libs\server\src\lib\read-schematic-collections.ts

The first one with the typ is exported in the barrel file, the other is seems is not used at all. I don't think this is causing the issue however, but you should fix it regardless.

**Comment by JoepKockelkorn** [comment]
I'm also experiencing this issue. I'm on MacOS and we are using version 8.8.0 of everything (cli + schematics).

**Comment by joelmuskwe** [comment]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Expecting for schematics to run.

## Current Behavior
Schematic not found in collection "@nrwl/workspace".

## Failure Information (for bugs)

```
> Executing task: ng generate @nrwl/workspace:demo test <

An unhandled exception occurred: Schematic "demo" not found in collection "@nrwl/workspace".
See "/private/var/folders/xr/7cp2hsfd139b6tx_t_tjysfw0000gn/T/ng-wUWqFS/angular-errors.log" for further details.
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```
angular-errors.log
```
[error] Error: Schematic "demo" not found in collection "@nrwl/workspace".
    at SchematicEngine.createSchematic (/Users/dev/Projects/lab/ng-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:232:23)
    at CollectionImpl.createSchematic (/Users/dev/Projects/lab/ng-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at GenerateCommand.getSchematic (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/schematic-command.js:135:27)
    at GenerateCommand.initialize (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/schematic-command.js:45:36)
    at async GenerateCommand.initialize (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/commands/generate-impl.js:12:9)
    at async GenerateCommand.validateAndRun (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/command-runner.js:186:24)
    at async default_1 (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/lib/cli/index.js:54:31)
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create-nx-workspace my-suite   (select angular)
2. ng generate @nrwl/workspace:workspace-schematic demo-schematic
3. ng generate @nrwl/workspace:demo-schematic hello
